externalHosts:
  - a01apvl00145.adeo.no
  - a01apvl00146.adeo.no
  - a01apvl00147.adeo.no
  - a01apvl00148.adeo.no
  - a01apvl00149.adeo.no
  - a01apvl00150.adeo.no
  - login.microsoftonline.com
  - hooks.slack.com
  - dokarkiv.prod-fss-pub.nais.io
  - pdl-api.prod-fss-pub.nais.io
springProfile: prod
kafka_pool: nav-prod